services:
  cassandra:
    image: bitnami/cassandra:4.0.7
    ports:
      - "127.0.0.1:9042:9042"
      - "127.0.0.1:7000:7000"
    environment:
      CASSANDRA_AUTHENTICATOR: AllowAllAuthenticator
      CASSANDRA_AUTHORIZER: AllowAllAuthorizer