version: "3.3"
services:
  cassandra:
    image: bitnami/cassandra:4.0.7
    ports:
      - "9042:9042"
      - "7000:7000"
    environment:
      CASSANDRA_AUTHENTICATOR: AllowAllAuthenticator
      CASSANDRA_AUTHORIZER: AllowAllAuthorizer
  kafka:
    image: memoriaio/kafka-docker:2022.19.0
    ports:
      - "9092:9092"
      - "9093:9093"